# -*- coding: utf-8 -*-
"""financial_cnn_forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EFHtrNAtPa27RvmQX4zUthcSKqXjNyio
"""

!pip install yfinance scipy scikit-learn tensorflow

!mkdir src
!mkdir outputs

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
from scipy.signal import stft
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

def load_data(ticker="AAPL", period="1y"):
    data = yf.download(ticker, period=period)
    return data['Close'].values

data = load_data()

scaler = MinMaxScaler()
data_scaled = scaler.fit_transform(data.reshape(-1,1)).flatten()

def generate_spectrogram(signal):
    f, t, Zxx = stft(signal, nperseg=32)
    return np.abs(Zxx)

spectrogram = generate_spectrogram(data_scaled)

window_size = 32
X, y = [], []

for i in range(len(data_scaled) - window_size):
    segment = data_scaled[i:i+window_size]
    spec = generate_spectrogram(segment)
    X.append(spec)
    y.append(data_scaled[i+window_size])

X = np.array(X)
y = np.array(y)

X = X.reshape(X.shape[0], X.shape[1], X.shape[2], 1)

split = int(0.8 * len(X))
X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=X.shape[1:]),
    MaxPooling2D((2,1)),
    Flatten(),
    Dense(64, activation='relu'),
    Dense(1)
])

model.compile(optimizer='adam', loss='mse')

model.fit(X_train, y_train, epochs=10, batch_size=16)

predictions = model.predict(X_test)

future_steps = 10
future_predictions = []

last_window = data_scaled[-window_size:]

for _ in range(future_steps):
    spec = generate_spectrogram(last_window)
    spec = spec.reshape(1, spec.shape[0], spec.shape[1], 1)

    next_pred = model.predict(spec)[0][0]
    future_predictions.append(next_pred)

    last_window = np.append(last_window[1:], next_pred)

predictions_rescaled = scaler.inverse_transform(predictions)
y_test_rescaled = scaler.inverse_transform(y_test.reshape(-1,1))
future_rescaled = scaler.inverse_transform(np.array(future_predictions).reshape(-1,1))

plt.figure(figsize=(10,5))

plt.plot(y_test_rescaled, label="Actual")
plt.plot(predictions_rescaled, label="Predicted")

plt.plot(range(len(y_test_rescaled), len(y_test_rescaled)+future_steps),
         future_rescaled, label="Future", linestyle='dashed')

plt.legend()
plt.title("Stock Prediction")
plt.savefig("outputs/prediction.png")
plt.show()

plt.imshow(spectrogram, aspect='auto', cmap='viridis')
plt.colorbar()
plt.title("Spectrogram")
plt.savefig("outputs/spectrogram.png")
plt.show()

!ls outputs

from google.colab import files

files.download("outputs/prediction.png")
files.download("outputs/spectrogram.png")